language: go
go:
- 1.11.x
os:
- osx
dist: trusty
env:
- GO111MODULE=on
script:
- go test ./...
- "./build.sh $(git describe --exact-match --tags $(git log -n1 --pretty='%h'))"
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: fops
  skip_cleanup: true
  on:
    repo: rybbchao/fops
    tags: true
