language: go
go:
- 1.11.x
os:
- osx
dist: trusty
env:
  matrix:
  - GO111MODULE=on
  global:
    secure: QLqlopPtFmORIoVNgog3BywJlcLbLb3NwWyuWTd3dlhk3gjIcKxnLXVi+glbzAVJ4c3yEzMVLWyWcHU7saaVJ8M0w54gKqRtJlzv+RxU/zPbM1PizzFb0yUpq6spigh0wbaQHEVj2Gan8ZrHRg3i7orzouQGmVj9zhaeUDSSPet5XgAXFkQvvsQwN2XHU8n+nkhONbsgWg1LtJZ4vVqcEcK9yUDLS8bbUyOs4hWeGleVHMkrlKua51xYZjmMuWHQlIvrm6Gkj8LU9xgMxT9gu74SndO+mTPlqyDFZan13EDwjGhz8z4YSbT6ItwgFm3fMdyYK/6RzQNADAA5857Ojox9LILoFuG5MuesX5S8WLiPogFC3kL4zmYXbJoPs66ysdK9ZxHngHdUM63N+nek5UwKAqixBfp7xt5Xf3xGVpnIv23UDBf+ndJ9KAj5i4N9skwjYutq1uA60axvEE+tQXZqCTYCUP/7Q4Te9evrMPgSLoy8PlEiQQFgrHKzzztE6Bk/bkpIV6SQhNuR0ReDl5/spqxyoboZezqGUTY8Om29gYOeWTx/Ajt+6fDm3yBt8Z39t9/aSejV4707lxLYrFgkJ1x5PSPH4LfjgRY1tlT+zkUnW3MSn7Y2Ck4g9Vyq1/2+8/cS0uiQEe1m9GP6ZZ05pidlHFOCEzucmURQTKk=
script:
- go test ./...
- "./build.sh $(git describe --exact-match --tags $(git log -n1 --pretty='%h'))"
deploy:
  provider: releases
  file: fops
  skip_cleanup: true
  on:
    repo: rybbchao/fops
    tags: true
before_install:
- |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

    # Decrypt the file containing the private key

    openssl aes-256-cbc \
      -K $encrypted_2db15d2523a7_key \
      -iv $encrypted_2db15d2523a7_iv \
      -in ".travis/github_deploy_key.enc" \
      -out "$SSH_FILE" -d

    # Enable SSH authentication

    chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
          "Host github.com" \
          "  IdentityFile $SSH_FILE" \
          "  LogLevel ERROR" >> ~/.ssh/config
